### ISSUE TITLE
Cannot use downloaded atlas as reference space

### ISSUE THREAD

**Issue by CHrlS98** [linum-uqam/m2m#154]
I want to download the projection data for some injection experiment. I do not need to work in a particular user space and would just like to use the actual Allen template converted to RAS as my reference space. Hence I would like to do something like:
```
m2m_download_template.py $AMBRA -r 100
m2m_compute_transform_matrix.py $AMBRA $MATRIX 100 100
m2m_import_proj_density.py $EXPERIMENT $AMBRA $MATRIX 100
```
However, the above lines result in the following when importing the projection density:
```
WARNING: In /project/itksource/Modules/Core/Common/include/itkImageBase.hxx, line 87
Image (0x55eed5dcfdc0): Negative spacing is not supported and may result in undefined behavior.
Proceeding to set spacing to [-25, -25, -25]
```
Also, the resulting images are empty.

I think this is a problem with the `stride` component in the output Allen reference nifti image (see output below) that messes up the transform matrix computed with `m2m_compute_transform_matrix.py`.
```
>>> mrinfo $AMBRA
************************************************
Image name:          "template_100um.nii.gz"
************************************************
  Dimensions:        456 x 528 x 320
  Voxel size:        0.025 x 0.025 x 0.025
  Data strides:      [ -1 -2 3 ]
  Format:            NIfTI-1.1 (GZip compressed)
  Data type:         unsigned 16 bit integer (little endian)
  Intensity scaling: offset = 0, multiplier = 1
  Transform:                    1          -0           0      -11.38
                               -0           1           0      -21.15
                               -0          -0           1           0
```

I managed to bypass the problem by "re-striding" the image using `mrtrix`'s `mrconvert`, but I think it would be better if it were done directly when downloading and converting the template. The actual command is given below and simply forces the `Data strides` field to `[1 2 3]`.
```
mrconvert $AMBRA $FIXED -strides 1,2,3
``` 

Is this a known issue and/or a wanted behaviour? 
If not, I could try drafting a PR for this.

See ya!

**Comment by joe-from-mtl** [comment]
We changed the way the Allen PIR volumes are reoriented to RAS during the template and atlas download. This should prevent negative strides when using the `m2m_download_template.py` and the `m2m_download_annotation.py` scripts.
